name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

#   Test:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3
#     - name: Build the Docker image
#       run: |
#        pip install pylint
#        pylint app.py

  Docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag kenkool23/python-app:${{github.run_number}}
      
    -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: |
         kenkool23/python-app:${{github.run_number}}
         kenkool23/python-app:latest

  Run-service:
    runs-on: ubuntu-latest
    needs: Docker
    steps:
      - name: Configure AWS Credentials For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Update Service
        run: aws ecs update-service --service app-serv-lbbb --cluster appCluster --force-new-deployment
