name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  Docker-image:
    runs-on: ubuntu-latest
    #needs: Test
    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag kenkool23/python-app:v.${{github.run_number}}
      
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    -
      name: push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: |
         kenkool23/python-app:v.${{github.run_number}}
         kenkool23/python-app:latest
    
