name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: created folder
      run: mkdir folder

    - name: List the direc
      run: ls -l

  deploy:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
    - name: List the direc
      run: ls -l
    
