name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  Code-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test App code
      run: echo "Testing python app"


  Docker-image:
    runs-on: ubuntu-latest
    needs: Code-scan
    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag kenkool23/python-app:v.${{github.run_number}}
      
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    -
      name: push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: |
         kenkool23/python-app:v.${{github.run_number}}
         kenkool23/python-app:latest

  Update-ECS-service:
    runs-on: ubuntu-latest
    needs: Docker-image
    steps:
      - name: Configure AWS Credentials For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update Service
        run: aws ecs update-service \
          --service app-serv-lb \
          --cluster app-cluster \
          --force-new-deployment
    
